// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKt3YYREnkQz1VOIDLBp4lPADhBxECJ7E',
    appId: '1:587613757437:web:895038d31cb267af6d8394',
    messagingSenderId: '587613757437',
    projectId: 'conecta-2f7b4',
    authDomain: 'conecta-2f7b4.firebaseapp.com',
    storageBucket: 'conecta-2f7b4.appspot.com',
    measurementId: 'G-1R0N2GSZG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzN00kbNrA-d0nKaVUrbUwx6QkyEuy9Qg',
    appId: '1:587613757437:android:1b4cfcc61542c1f26d8394',
    messagingSenderId: '587613757437',
    projectId: 'conecta-2f7b4',
    storageBucket: 'conecta-2f7b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDkHPa-nF5Y2Gu9KZUAID-20TqkhhTex4',
    appId: '1:587613757437:ios:c9c6dae08680d4c16d8394',
    messagingSenderId: '587613757437',
    projectId: 'conecta-2f7b4',
    storageBucket: 'conecta-2f7b4.appspot.com',
    iosClientId: '587613757437-3rcv945o1mc3fcufg5hpf98d8sgvn77i.apps.googleusercontent.com',
    iosBundleId: 'com.example.conecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDkHPa-nF5Y2Gu9KZUAID-20TqkhhTex4',
    appId: '1:587613757437:ios:283de6becd467a3a6d8394',
    messagingSenderId: '587613757437',
    projectId: 'conecta-2f7b4',
    storageBucket: 'conecta-2f7b4.appspot.com',
    iosClientId: '587613757437-qfnupl2vd4k4rud6etiv084jsdde0c99.apps.googleusercontent.com',
    iosBundleId: 'com.example.conecta.RunnerTests',
  );
}
